### ISSUE TITLE
diversity-richness-biomass-hotspots

### ISSUE THREAD

**Issue by cole-fields** [dfo-msea/GIS-Hub-Layers#1]
Biomass_Hotspot_Fish_Trawl, Biomass_Hotspot_Invert_Trawl, Diversity_Hotspot_Fish_Longline, Diversity_Hotspot_Fish_Trawl, Diversity_Hotspot_Invert_Trawl
 - [x] add field descriptions for polygongrp, shape_leng, buff_dist, orig_fid, area_km2, override, ruleid (or delete if unnecessary) 

- [x] HabitatRichness_Hotspot_Nearshore, Longline_Data_Footprint, Trawl_Data_Footprint:
 - [x] add field descriptions for source_id, gi_bin, ruleid, override (or delete if unnecessary)

**Comment by cole-fields** [comment]
testing assigning task to user

**Comment by kspgale** [comment]
Fields fixed and gdb re-uploaded

**Comment by cole-fields** [comment]
This looks good, thanks for the fix. Only potential thing I noticed was some feature classes have an unknown projection code (https://www.gis-hub.ca/dataset/diversity-richness-biomass-hotspots/resource/56b12099-1734-4741-b661-bb2d4461b752). 

Likely has same parameters as albers EPSG 3005, not a problem for analysis. Just a note.

**Comment by kspgale** [comment]
Fixed and re-uploaded
