### ISSUE TITLE
Old links to gitlab or github

### ISSUE THREAD

**Issue by jnephin** [dfo-msea/GIS-Hub-Layers#8]
Search datasets in the GISHub and update any outdated links to gitlab or github. Update with links to dfo-msea page.
- [ ] enable hyperlink in the 'Scripts or Software Routines' metadata field (create issue for Michael)
- [x] update link to dfo-msea repo for oceanographic layers
- [x] transfer https://github.com/kspgale/ebsas-2018 to dfo-msea and update metadata for Scripts or Software Routines @kspgale
- [x] update script reference https://www.gis-hub.ca/dataset/floating-structures to dfo-msea @cole-fields
- [x] add script reference to https://www.gis-hub.ca/dataset/substrate100m-data @cole-fields
- [x] add script reference to https://www.gis-hub.ca/dataset/substrate20m (will need to update if we use Ed's modified code where he switched to Ranger R package) @cole-fields
- [x] add script reference to https://www.gis-hub.ca/dataset/coastline-fetch-bc @cole-fields
- [x] update script reference in description of change to https://www.gis-hub.ca/dataset/coastline-fetch-bc @cole-fields

**Comment by jnephin** [comment]
I found the current, temp, salinity data has an old link to my gitlab page in the methods text. Is there a better spot to link to the code that is more visible? As its own metadata heading with a working url link maybe?

**Comment by cole-fields** [comment]
Yes, any URLs to code repositories or paths to code on the spatial datasets drive/other should be included in the 'Scripts or Software Routines' metadata field. See https://www.gis-hub.ca/dataset/gridded-nearshore-fetch as an example. Annoyingly, doesn't create a hyperlink from the URL, but can see if that can be added.

**Comment by cole-fields** [comment]
I removed the old link from the methods, and updated the URL to the dfo-msea repository for the oceanographic layers metadata. I think the URL should only be in the scrips of software routines field in metadata, not in methods also. otherwise harder to update.

**Comment by cole-fields** [comment]
all old references should be updated now. I've created an issue for Michael to enable hyperlinks for URLs in the scripts metadata field.

**Comment by jnephin** [comment]
Great - thanks for fixing all those
